In [50]:
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional

In [51]:
data = [[i for i in range(100)]]
data = np.array(data, dtype=float)

In [52]:
data

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
        39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
        52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
        65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
        78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
        91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [54]:
target = [[i for i in range(1,101)]]
target = np.array(target, dtype=float)
target

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
         34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
         78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
         89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
        100.]])

In [59]:
data = data.reshape((1,1,100))  

In [62]:
data

array([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
         36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
         48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.,
         60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71.,
         72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83.,
         84., 85., 86., 87., 88., 89., 90., 91., 92., 93., 94., 95.,
         96., 97., 98., 99.]]])

In [63]:
target

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
         34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
         45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
         56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
         78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
         89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
        100.]])

In [64]:
x_test=[i for i in range(100,200)]
x_test=np.array(x_test,dtype=float).reshape((1,1,100));
y_test=[i for i in range(101,201)]
y_test=np.array(y_test,dtype=float)

In [ ]:
model = Sequential()  
model.add(LSTM(100,return_sequences=True,input_shape=(1,100)))
model.add(Dense(100))
model.compile(loss='mean_absolute_error', optimizer='adam',metrics=['accuracy'])
model.fit(data, target, epochs=1000, batch_size=3, validation_split=0.3,verbose=2)



Epoch 1/1000


In [47]:
pred=model.predict(data)
pred

array([[[ 0.9976126,  2.0017998,  2.9962587,  4.0067997,  5.004245 ,
          5.998355 ,  7.0023656,  7.997696 ,  8.997485 , 10.00241  ,
         11.00747  , 11.999789 , 12.994541 , 14.000457 , 14.999007 ,
         16.002775 , 16.998508 , 17.998074 , 18.995672 , 19.996534 ,
         20.671621 , 21.39873  , 20.073679 , 20.61903  , 21.387224 ,
         20.493517 , 21.736969 , 20.827105 , 20.246565 , 21.01225  ,
         21.382446 , 21.253899 , 20.163822 , 20.982008 , 21.567898 ,
         21.198746 , 21.265099 , 20.78324  , 20.727272 , 20.647615 ,
         21.135117 , 21.291529 , 21.050465 , 20.930922 , 20.427832 ,
         21.375753 , 21.015549 , 20.637516 , 21.20573  , 20.957832 ,
         20.595324 , 21.256407 , 21.046824 , 20.810871 , 20.671637 ,
         20.855757 , 21.508373 , 20.871777 , 21.128555 , 20.496052 ,
         20.684547 , 20.838331 , 20.88356  , 21.202005 , 20.212345 ,
         20.68023  , 20.89711  , 20.918188 , 20.728941 , 20.751993 ,
         20.779974 , 20.817978 , 2